# Generated by Django 5.2.13 on 2026-04-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_tags_event_tags_alter_company_companyowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyOwner',
            field=models.ForeignKey(
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='owned_company', 
                to='api.user'
            ),
        ),
    ]
