# Generated by Django 5.2.13 on 2026-04-22 12:13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260422_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyOwner',
            field=models.ForeignKey(
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='ownedCompany', 
                to='api.user'
            ),
        ),
    ]
