# Generated by Django 5.2.13 on 2026-04-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_companyowner_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyOwner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='artistPhoto',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='companyPhoto',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='event',
        ),
    ]
