# Generated by Django 5.2.13 on 2026-04-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='soldOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='artistImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.artist'),
        ),
        migrations.AddField(
            model_name='photo',
            name='companyImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='photo',
            name='eventImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
