# Generated by Django 5.2.13 on 2026-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_notification_user_event_soldout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isCon',
            field=models.BooleanField(default=False),
        ),
    ]
