# Generated by Django 5.2.13 on 2026-04-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_iscon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
