# Generated by Django 5.2.13 on 2026-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_latitude_event_longitude_user_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
