# Generated by Django 5.2.13 on 2026-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
