# Generated by Django 5.2.13 on 2026-04-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
