# Generated by Django 5.2.13 on 2026-04-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_event_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numberOfFollowers',
            field=models.IntegerField(default=0),
        ),
    ]
