# Generated by Django 5.2.13 on 2026-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_numberoffollowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='company',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='followedArtists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='api.artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='followedCompanies',
            field=models.ManyToManyField(blank=True, related_name='followers', to='api.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='followedEvents',
            field=models.ManyToManyField(blank=True, related_name='followers', to='api.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
