# Generated by Django 5.2.13 on 2026-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_hasspotify_spotifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotifyId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
