# Generated by Django 5.2.13 on 2026-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_artist_spotifyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='regon',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
